name: Run API Handler

on:
  schedule:
    - cron: '0 12 * * *'  # 每天中午12点执行
  workflow_dispatch:  # 添加手动触发功能

jobs:
  run-api-handler:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Run API Handler
      env:
        SENDGRIDAPIKEY: ${{ secrets.SENDGRIDAPIKEY }}
        MYEMAIL: ${{ secrets.MYEMAIL }}
      run: |
        python api_handler.py